<?php

use App\Core\DataLayer\Seeder\Seeder;

return Seeder::table('corsi')
    ->row([
        'title' => 'Laravel - La Guida Completa',
        'overview' => "<p><strong>Laravel: La Guida Completa</strong> è il corso definitivo per chiunque voglia imparare a padroneggiare Laravel, uno dei framework PHP più popolari. Dedicato sia ai principianti che a chi ha già esperienza con PHP, questo corso copre tutto, dalle basi alle funzionalità avanzate di Laravel, permettendo di creare applicazioni web performanti e sicure.</p><p>Il corso include sezioni come:</p><p><strong>Introduzione al framework Laravel</strong>: capirai perché Laravel è diventato così rilevante per il mondo del web development.</p><p><strong>Installazione e Configurazione</strong>: scoprirai i requisiti e le versioni compatibili, nonché come configurare l'ambiente.</p><p><strong>Concetti Fondamentali</strong>: routing, controllers, views, e gestione dei dati con Eloquent ORM.</p><p><strong>Funzionalità Avanzate</strong>: middlewares, sicurezza, autenticazione, e caching.</p><p>Il metodo di insegnamento è chiaro e pratico, con esempi applicabili e progetti reali. Il docente incoraggia il feedback degli studenti, per rendere il corso sempre più rispondente alle esigenze del pubblico.</p>",
        'link' => 'https://www.udemy.com/certificate/UC-747da1d6-62da-455c-ab93-9234bb17a254/',
        'certified' => 2024,
        'ente' => 'Udemy - Alfonso Casegna',
    ])
    ->row([
        'title' => 'FullStack Java Developer',
        'overview' => "<p>Ho completato un corso di programmazione Fullstack in Java utilizzando Java Enterprise Edition (JEE) e Eclipse come ambiente di sviluppo integrato. Durante questo percorso, ho acquisito competenze fondamentali per lo sviluppo di applicazioni web complete, coprendo sia il lato client che il lato server.</p><p><strong>Introduzione a JEE</strong>: Ho esplorato i concetti chiave di Java Enterprise Edition, comprendendo come JEE faciliti lo sviluppo di applicazioni scalabili e robuste attraverso l'uso di componenti modulari.</p><p><strong>Sviluppo Backend</strong>: Ho imparato a creare e gestire applicazioni backend utilizzando Servlets e JSP, permettendomi di gestire la logica dell'applicazione e l'interazione con il database. Ho approfondito anche l'integrazione con framework come Hibernate per la gestione della persistenza dei dati.</p><p><strong>Sviluppo Frontend</strong>: Ho lavorato con tecnologie web moderne come HTML, CSS e JavaScript per creare interfacce utente responsive e dinamiche, garantendo una buona esperienza utente.</p><p><strong>Framework MVC</strong>: Ho implementato il pattern Model-View-Controller (MVC) per separare la logica di business dalla presentazione, facilitando la manutenibilità e la scalabilità delle applicazioni.</p><p><strong>Progetti Pratici</strong>: Attraverso esercitazioni pratiche e progetti reali, ho avuto l'opportunità di applicare le mie competenze in scenari concreti, costruendo applicazioni web complete che integrano tutte le tecnologie apprese.</p>",
        'link' => 'https://drive.google.com/file/d/1XvBH8OAEozA_opjGj3N4xmTCPsKlPGoM/view',
        'certified' => 2023,
        'ente' => 'ItConsulting',
    ])
    ->row([
        'title' => 'Sviluppo Applicazioni MVC PHP 8',
        'overview' => "<p><strong>Architettura MVC</strong>: Implementazione della separazione logica tramite i componenti Model, View e Controller, per una gestione modulare del codice.</p><p><strong>Gestione Richieste e Risposte</strong>: Utilizzo di routing avanzato e manipolazione delle richieste HTTP per dirigere le azioni di controller appropriate.</p><p><strong>Integrazione con Database tramite PDO</strong>: Connessione sicura e gestita al database per tutte le operazioni CRUD.</p><p><strong>Gestione Sessioni e Autenticazione</strong>: Configurazione di sessioni per autenticazione e persistenza dei dati.</p><p><strong>Gestione File e Invio Email (SMTP)</strong>: Implementazione di funzionalità di caricamento file sicure e connessione SMTP per l'invio di email.</p><p><strong>Middleware e Gestione delle Eccezioni</strong>: Inserimento di middleware per elaborazioni personalizzate e gestione delle eccezioni</p>",
        'link' => 'https://www.udemy.com/certificate/UC-7c3cb35d-6d2c-4790-a70a-24695f74ee18/',
        'certified' => 2024,
        'ente' => 'Udemy - Gianluca Scocozza',
    ])
    ->row([
        'title' => 'Introduzione a Python',
        'overview' => "<p>Ho completato un corso introduttivo di Python, un linguaggio di programmazione versatile e potente, ampiamente utilizzato per lo sviluppo web, l'analisi dei dati e l'automazione. Durante il corso, ho acquisito una solida base nelle principali caratteristiche di Python, essenziale per chi desidera intraprendere un percorso nel mondo della programmazione.</p><p><strong>Fondamenti di Python</strong>: Ho esplorato la sintassi di base, comprendendo come scrivere e eseguire script Python. Ho appreso le strutture di controllo del flusso, come cicli e condizioni, per gestire la logica dei programmi.</p><p><strong>Tipi di Dati e Strutture</strong>: Ho imparato a lavorare con variabili, liste, tuple, dizionari e set, gestendo i dati in modo efficace e comprendendo le differenze tra queste strutture.</p><p><strong>Funzioni e Moduli</strong>: Ho acquisito competenze nella creazione di funzioni per organizzare il codice e migliorare la riutilizzabilità, nonché nell'importazione di moduli per ampliare le funzionalità dei miei programmi.</p><p><strong>Gestione degli Errori</strong>: Ho scoperto come gestire le eccezioni in Python, garantendo che i miei programmi potessero affrontare situazioni impreviste senza bloccarsi.</p><p><strong>Progetti Pratici</strong>: Durante il corso, ho avuto l'opportunità di lavorare su progetti pratici, applicando le competenze apprese per creare semplici applicazioni, automatizzare compiti e analizzare dati.</p>",
        'link' => 'https://accademiadomani.org/studenti/pluginfile.php/1/tool_certificate/issues/1704196387/8260925312LI.pdf',
        'certified' => 2024,
        'ente' => 'Accademia Domani',
    ])
    ->row([
        'title' => 'Developer Java',
        'overview' => "<p>Ho completato un corso di Java base con NetBeans che ha gettato solide fondamenta nella programmazione orientata agli oggetti e nell'utilizzo delle interfacce grafiche. Ecco cosa ho appreso durante questo entusiasmante viaggio:</p><p><strong>Introduzione a Java</strong>: Ho iniziato esplorando le basi del linguaggio Java, comprendendo la sintassi, i tipi di dati e le strutture di controllo. Questi elementi sono stati essenziali per la mia crescita come sviluppatore.</p><p><strong>Programmazione Orientata agli Oggetti (OOP)</strong>: Ho approfondito i principi fondamentali dell'OOP, come classi, oggetti, ereditarietà e polimorfismo. Questi concetti mi hanno permesso di scrivere codice più modulare e riutilizzabile.</p><p><strong>Java GUI</strong>: Una parte fondamentale del corso è stata dedicata all'interfaccia grafica. Ho imparato a creare applicazioni con Java Swing, progettando interfacce utente interattive e accattivanti, che migliorano l'esperienza dell'utente.</p><p><strong>Gestione degli Eventi</strong>: Ho scoperto come gestire gli eventi dell'interfaccia utente, consentendo interazioni dinamiche e reattive nelle applicazioni sviluppate. Questa competenza è fondamentale per rendere le applicazioni più coinvolgenti.</p><p><strong>Applicazioni Pratiche</strong>: Attraverso esercizi pratici e progetti, ho applicato le mie conoscenze in scenari reali, imparando a risolvere problemi e ottimizzare il codice per una migliore performance.</p>",
        'link' => 'https://drive.google.com/file/d/14k6s0Pw6h0t7PhAkQ1TzkqMkR0-kNzoN/view',
        'certified' => 2023,
        'ente' => 'Gamma Accademy',
    ])
    ->row([
        'title' => 'Javascript',
        'overview' => "<p><strong>Novità di ECMAScript</strong>: Ho avuto l'opportunità di immergermi nelle innovazioni di ECMAScript 6 e versioni successive, come le arrow functions e la destrutturazione, che hanno reso il mio codice più elegante e diretto.</p><p><strong>Manipolazione del DOM</strong>: Ho appreso l'arte di interagire con il DOM, consentendomi di modificare e aggiornare le pagine web in modo dinamico, per un'esperienza utente interattiva.</p><p><strong>Gestione degli Eventi</strong>: Ho scoperto come gestire gli eventi per rendere le mie applicazioni più reattive e coinvolgenti, permettendo agli utenti di interagire in tempo reale.</p><p><strong>Asincronia con Promesse e Async/Await</strong>: Ho imparato a gestire le operazioni asincrone attraverso promesse e la sintassi async/await, facilitando la scrittura di codice che gestisce il tempo in modo più fluido e leggibile.</p><p>&nbsp;</p>",
        'link' => 'https://accademiadomani.org/studenti/pluginfile.php/1/tool_certificate/issues/1675556950/0836180474LI.pdf',
        'certified' => 2023,
        'ente' => 'Accademia Domani',
    ])
    ->row([
        'title' => 'SQL con MySQL e SQL Server',
        'overview' => "<p>Ho completato un corso dedicato a SQL e SQL Server, incentrato sulle competenze necessarie per gestire e manipolare basi di dati in modo efficace. Durante il corso, ho approfondito i seguenti argomenti:</p><p><strong>Fondamenti di SQL</strong>: Ho appreso le basi del linguaggio SQL, comprendendo la sintassi e le principali operazioni per la creazione, lettura, aggiornamento e cancellazione (CRUD) dei dati.</p><p><strong>Interrogazioni Avanzate</strong>: Ho esplorato tecniche per scrivere query avanzate, incluse le join, le subquery e le funzioni aggregate, per estrarre e analizzare dati complessi.</p><p><strong>Gestione delle Basi di Dati</strong>: Ho imparato a progettare e gestire basi di dati relazionali, creando tabelle, relazioni e vincoli per garantire l'integrità dei dati.</p><p><strong>SQL Server</strong>: Ho acquisito competenze specifiche su SQL Server, inclusa l'installazione, la configurazione e l'ottimizzazione delle performance delle basi di dati.</p><p><strong>Stored Procedures e Trigger</strong>: Ho studiato come creare e utilizzare stored procedures e trigger per automatizzare processi e garantire operazioni coerenti all'interno del database.</p><p><strong>Sicurezza dei Dati</strong>: Ho esplorato le pratiche migliori per garantire la sicurezza dei dati, inclusi controlli di accesso e gestione delle autorizzazioni.</p>",
        'link' => 'https://drive.google.com/file/d/1gHB8EK13k912xoJP23AeXzDV2KJK0QGP/view',
        'certified' => 2023,
        'ente' => 'Accademia Domani',
    ])
    ->row([
        'title' => 'Developer PHP',
        'overview' => "<p>Ho completato un corso di aggiornamento per diventare sviluppatore web, dove ho approfondito un ampio ventaglio di tecnologie essenziali per lo sviluppo di applicazioni web moderne. Durante il corso, ho acquisito competenze pratiche nelle seguenti aree:</p><p><strong>HTML</strong>: Ho imparato a strutturare il contenuto delle pagine web utilizzando le best practices per un markup semantico e accessibile.</p><p><strong>CSS</strong>: Ho esplorato le tecniche di styling per migliorare l'aspetto visivo delle pagine web, inclusi layout responsive e design accattivante.</p><p><strong>JavaScript</strong>: Ho approfondito le funzionalità di JavaScript per rendere le pagine interattive e dinamiche, implementando script per migliorare l'esperienza utente.</p><p><strong>Bootstrap</strong>: Ho utilizzato Bootstrap come framework CSS per creare layout reattivi e mobile-friendly in modo rapido ed efficiente.</p><p><strong>PHP</strong>: Ho acquisito competenze nel linguaggio PHP, imparando a scrivere script per la logica di backend e a gestire le interazioni con i dati.</p><p><strong>SQL</strong>: Ho imparato a utilizzare SQL per gestire le basi di dati, effettuando query e operazioni di CRUD (Create, Read, Update, Delete) per integrare i dati nelle mie applicazioni web.</p><p>Questo corso mi ha fornito una base solida e le competenze necessarie per sviluppare applicazioni web complete e interattive, preparandomi per le sfide del mondo del web development.</p>",
        'link' => 'https://drive.google.com/file/d/1M3kOxy6ZRaPz3Sdb7zG9_3L9uFJpJ6cC/view',
        'certified' => 2022,
        'ente' => 'AVS Studio',
    ])
    ->row([
        'title' => 'HTML, Javascript e SVG',
        'overview' => "<p>Ho recentemente completato un corso di aggiornamento su <strong>HTML, JavaScript e SVG</strong>, fondamentale per restare al passo con le ultime tecnologie nel campo dello sviluppo web. Questo corso mi ha permesso di approfondire e aggiornare le mie competenze, essenziali per la creazione di siti web moderni e interattivi.</p><p><strong>Cosa ho imparato:</strong></p><p><strong>Aggiornamenti su HTML</strong>: Ho esplorato le nuove funzionalità e best practices di HTML5, migliorando la mia capacità di creare markup semantico e accessibile.</p><p><strong>Tecniche Avanzate di JavaScript</strong>: Ho approfondito le nuove funzionalità di JavaScript, inclusi ES6 e le ultime API, per sviluppare applicazioni web più fluide e reattive.</p><p><strong>SVG per Grafica Vettoriale</strong>: Ho imparato a utilizzare SVG non solo per creare grafiche, ma anche per implementare animazioni e interazioni che arricchiscono l'esperienza utente.</p><p><strong>Integrazione delle Tecnologie</strong>: Ho scoperto come combinare HTML, JavaScript e SVG per costruire progetti complessi e dinamici, migliorando l'interazione e l'estetica dei miei siti web.</p><p><strong>Strumenti di Debugging e Sviluppo</strong>: Ho acquisito competenze nell'uso di strumenti moderni per il debugging e l'ottimizzazione del codice, aumentando la mia efficienza come sviluppatore.</p>",
        'link' => 'https://drive.google.com/file/d/1RkXRkJIxGeo2-fg2VpZdiVHSIw665o_m/view',
        'certified' => 2023,
        'ente' => 'Accademia Domani',
    ])
    ->row([
        'title' => 'Web Builder con Wordpress',
        'overview' => "<p>In questo corso di <strong>Web Builder con WordPress</strong>, ho imparato a costruire siti web da zero in modo semplice e intuitivo. Ho esplorato l'interfaccia di WordPress e ho acquisito competenze pratiche che mi hanno permesso di creare pagine accattivanti senza dover scrivere codice.</p><p><strong>Cosa ho imparato:</strong></p><p><strong>Introduzione a WordPress</strong>: Ho capito come funziona WordPress e perché è una delle piattaforme più popolari per la creazione di siti web.</p><p><strong>Creazione di un Sito Web</strong>: Ho imparato a impostare il mio sito, dalla registrazione del dominio all'hosting, rendendo il processo accessibile a chiunque.</p><p><strong>Utilizzo di Temi e Plugin</strong>: Ho scoperto come scegliere e installare temi per personalizzare l'aspetto del mio sito e come utilizzare plugin per aggiungere funzionalità extra.</p><p><strong>Gestione dei Contenuti</strong>: Ho praticato la creazione e la pubblicazione di post e pagine, ottimizzando il contenuto per attrarre visitatori.</p><p><strong>SEO per Principianti</strong>: Ho acquisito le basi dell'ottimizzazione per i motori di ricerca, il che mi ha aiutato a rendere il mio sito più visibile online.</p><p><strong>Sicurezza del Sito</strong>: Ho appreso le migliori pratiche per proteggere il mio sito da minacce comuni.</p><p><strong>Supporto e Community</strong>: Ho scoperto l'importanza di connettermi con altri partecipanti e esperti per condividere esperienze e risolvere problemi.</p>",
        'link' => 'https://drive.google.com/file/d/11sQ5TYRO07So3qmhgTYKDK2a9T75mBop/view',
        'certified' => 2021,
        'ente' => 'Avs Studio',
    ]);
